---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-keycloak-postgres
  namespace: my
spec:
  replicas: 1
  revisionHistoryLimit: 0  # Set to 0 to keep no old ReplicaSets
  selector:
    matchLabels:
      app: my-keycloak-postgres
  template:
    metadata:
      labels:
        app: my-keycloak-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: my-keycloak-postgres
              key: pg_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-keycloak-postgres
              key: pg_password
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: my-keycloak-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: my-keycloak-postgres
  namespace: my
spec:
  selector:
    app: my-keycloak-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
