---
apiVersion: v1
kind: Secret
metadata:
  name: my-meilisearch-master-key-secret
  namespace: my
type: Opaque
stringData: # means contains arbitrary string data
  master_key: <put-your-plain-text-here> # put your plain text password here

---
apiVersion: v1
kind: Secret
metadata:
  name: my-keycloak-postgres
  namespace: my
  labels:
    app: my-keycloak-postgres
type: Opaque
stringData: # means contains arbitrary string data
  pg_user: keycloak
  pg_password: <put-your-plain-text-here> # put your plain text password here


---
apiVersion: v1
kind: Secret
metadata:
  name: my-keycloak
  namespace: my
  labels:
    app: my-keycloak
type: Opaque
stringData: # means contains arbitrary string data
  admin: admin
  password: <put-your-plain-text-here> # put your plain text password here
