apiVersion: v1
kind: Secret
metadata:
  name: my-keycloak-postgres-password-secret
  namespace: my
type: Opaque
data:
  password: <base64-encoded-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: my-keycloak-admin-password-secret
  namespace: my
type: Opaque
data:
  password: <base64-encoded-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: my-meilisearch-master-key-secret
  namespace: my
type: Opaque
data:
  password: <base64-encoded-password>
