---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-storefront
  namespace: noscai
  annotations:
    traefik.ingress.kubernetes.io/ssl-cert: "noscai-my-id-tls-secret" # Reference the secret
    traefik.ingress.kubernetes.io/ssl-redirect: "true" # Enforce HTTPS
spec:
  rules:
  - host: dev-storefront.noscai.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-storefront
            port:
              number: 8000
  tls:
  - hosts:
    - dev-storefront.noscai.my.id
    secretName: noscai-my-id-tls-secret


---
apiVersion: v1
kind: Endpoints
metadata:
  name: dev-storefront
  namespace: noscai
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: dev-storefront
  namespace: noscai  # Adjust namespace if needed
spec:
  type: ClusterIP
  selector:
    app: dev-storefront
  ports:
    - port: 8000
      targetPort: 8000
